- name: Import Sublime Text GPG key
  command: rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg

- name: Add Sublime Text repo
  yum: 
    name: yum-utils 

- command: yum-config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo

- name: Install Sublime Text
  yum:
    name: sublime-text

- name: Install Package Control
  file:
    path: /home/{{ local_username }}/.config/sublime-text-3/Installed Packages/
    state: directory
    owner: "{{ local_username }}"
    group: "{{ local_username }}" 
    mode: 0700

- get_url: 
    url: https://packagecontrol.io/Package Control.sublime-package
    dest: /home/{{ local_username }}/.config/sublime-text-3/Installed Packages/