- name: Get Terraform version
  shell: /usr/local/bin/terraform version | awk '{print $2}' | sed 's/v//' | tr -d '\n'
  ignore_errors: yes
  register: terraform_version_installed

- name: Download Terraform
  get_url:
    url: "{{ terraform_download_url }}"
    dest: "/tmp/{{ terraform_zip }}"
  when: terraform_version_installed.stdout != terraform_version

- name: Install unzip
  yum:
    name: unzip

- name: Extract Terraform
  unarchive:
    remote_src: yes
    src: /tmp/{{ terraform_zip }}
    dest: /usr/local/bin/
  when: terraform_version_installed.stdout != terraform_version

- file: 
    path: /usr/local/bin/terraform
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Cleanup Terraform Download
  file: 
    path: /tmp/{{ terraform_zip }}
    state: absent
