- name: "Configure Prometheus"
  file: 
    name: /opt/prometheus/data
    state: directory
    owner: root
    group: root

- template: 
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
    owner: root
    group: root

- template:
    src: run-prometheus-and-grafana.sh
    dest: /opt/prometheus/run-prometheus-and-grafana.sh
    mode: 0700
    owner: root
    group: root

- name: "Start Prometheus and Grafana"
  command: /opt/prometheus/run-prometheus-and-grafana.sh
  ignore_errors: yes