- name: Install Docker repo
  yum: name=yum-utils state=present

- command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum: name=docker-ce state=present

- name: Configure docker
  file:
    path: /etc/docker
    state: directory
    mode: 0700
    owner: root
    group: root

- template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Start Docker
  service: name=docker state=started enabled=true

- name: Add user to group
  user: name={{ local_username}} append=yes groups=docker

- name: Get Docker Compose version
  shell: /usr/local/bin/docker-compose version --short | tr -d '\n'
  ignore_errors: yes
  register: docker_compose_version_installed

- name: Download Docker Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
  when: docker_compose_version_installed.stdout != docker_compose_version

- file:
    path: /usr/local/bin/docker-compose
    mode: 0755
    owner: root
    group: root